language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

jobs:
  allow_failures:
    - python: "3.7"
    - python: "3.8"

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox

script:
  - tox -e py